name: Java CI with Spring Boot + Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: Start Spring Boot dev server
        run: |
          nohup mvn spring-boot:run > app.log 2>&1 &
          echo "Waiting for Spring Boot to start..."
          sleep 30

      - name: Run tests (with unique Chrome profile)
        env:
          CHROME_OPTS: "--no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-$(date +%s)"
        run: |
          echo "Running Selenium tests..."
          mvn test -Dwebdriver.chrome.args="$CHROME_OPTS"

      - name: Show test results
        if: always()
        run: |
          mvn surefire-report:report || true
          echo "Test logs:"
          cat target/surefire-reports/*.txt || true

      - name: Upload test logs (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: target/surefire-reports/
